*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LZFRC1V01 .

FUNCTION $$UNIT$$ Z_BAPI_EPM_SO_ITEM_CREATE

    IMPORTING
       VALUE(SO_ID) TYPE !SNWD_SO_ID
       VALUE(SOITEMDATA) TYPE !BAPI_EPM_SO_ITEM
       VALUE(SOITEMDATAX) TYPE !BAPI_EPM_SO_ITEMX
       VALUE(PERSIST_TO_DB) TYPE !BAPI_EPM_BOOLEAN DEFAULT ABAP_TRUE
    EXPORTING
       VALUE(SO_ITEM_POS) TYPE !SNWD_SO_ITEM_POS
    TABLES
       !RETURN STRUCTURE !BAPIRET2 OPTIONAL .