*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY               **
*   NEVER CHANGE IT MANUALLY, PLEASE!                            **
*******************************************************************
FORM Z_BAPI_EPM_SO_ITEM_DELETE %_RFC.
* Parameter declaration
DATA SO_ID TYPE
SNWD_SO_ID
.
DATA SO_ITEM_POS TYPE
SNWD_SO_ITEM_POS
.
DATA PERSIST_TO_DB TYPE
BAPI_EPM_BOOLEAN
.
DATA BEGIN OF RETURN OCCURS 10.
INCLUDE STRUCTURE
BAPIRET2.
DATA END OF RETURN
.
* Assign default values
  PERSIST_TO_DB = ABAP_TRUE .
* Call remote function
  CALL FUNCTION 'Z_BAPI_EPM_SO_ITEM_DELETE' %_RFC
     EXPORTING
       SO_ID = SO_ID
       SO_ITEM_POS = SO_ITEM_POS
       PERSIST_TO_DB = PERSIST_TO_DB
     TABLES
       RETURN = RETURN
  .
ENDFORM.