*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LZFRC1V03 .

FUNCTION $$UNIT$$ Z_BAPI_EPM_SO_ITEM_DELETE

    IMPORTING
       VALUE(SO_ID) TYPE !SNWD_SO_ID
       VALUE(SO_ITEM_POS) TYPE !SNWD_SO_ITEM_POS
       VALUE(PERSIST_TO_DB) TYPE !BAPI_EPM_BOOLEAN DEFAULT ABAP_TRUE
    TABLES
       !RETURN STRUCTURE !BAPIRET2 OPTIONAL .