*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
INCLUDE LZFRC1V02 .

FUNCTION $$UNIT$$ Z_BAPI_EPM_SO_ITEM_GET_DETAIL

    IMPORTING
       VALUE(SO_ID) TYPE !SNWD_SO_ID
       VALUE(SO_ITEM_POS) TYPE !SNWD_SO_ITEM_POS
    EXPORTING
       VALUE(HEADERDATA) TYPE !BAPI_EPM_SO_HEADER
    TABLES
       !ITEMDATA STRUCTURE !BAPI_EPM_SO_ITEM OPTIONAL
       !RETURN STRUCTURE !BAPIRET2 OPTIONAL .