*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZFRC1U02.
                    "Z_BAPI_EPM_SO_ITEM_GET_DETAIL
INCLUDE LZFRC1U01.
                    "Z_BAPI_EPM_SO_ITEM_CREATE
INCLUDE LZFRC1U03.
                    "Z_BAPI_EPM_SO_ITEM_DELETE