interface ZIF_I_INVENTORY_TP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_INVENTORY_TP,
 CREATE_ZI_INVENTORY_TP         TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B488C2',
 DELETE_ZI_INVENTORY_TP         TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B508C2',
 LOCK_ZI_INVENTORY_TP           TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B3C8C2',
 SAVE_ZI_INVENTORY_TP           TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B588C2',
 UNLOCK_ZI_INVENTORY_TP         TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B408C2',
 UPDATE_ZI_INVENTORY_TP         TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B4C8C2',
 VALIDATE_ZI_INVENTORY_TP       TYPE /BOBF/ACT_KEY VALUE '0242AC1100021EDF97CE6716D7B548C2',
      END OF ZI_INVENTORY_TP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_INVENTORY_TP,
        BEGIN OF LOCK_ZI_INVENTORY_TP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_INVENTORY_TP,
        BEGIN OF UNLOCK_ZI_INVENTORY_TP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_INVENTORY_TP,
      END OF ZI_INVENTORY_TP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_INVENTORY_TP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0242AC1100021EDF97CE67433BD3A8C2',
      END OF ZI_INVENTORY_TP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_INVENTORY_TP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B3A8C2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B368C2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B468C2',
      END OF ZI_INVENTORY_TP,
      BEGIN OF ZI_INVENTORY_TP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B5E8C2',
      END OF ZI_INVENTORY_TP_LOCK,
      BEGIN OF ZI_INVENTORY_TP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B5C8C2',
      END OF ZI_INVENTORY_TP_MESSAGE,
      BEGIN OF ZI_INVENTORY_TP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100021EDF97CE6716D7B608C2',
      END OF ZI_INVENTORY_TP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_INVENTORY_TP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_INVENTORY_TP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0242AC1100021EDF97CE6716D7B2C8C2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_INVENTORY_TP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_INVENTORY_TP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0242AC1100021EDF97CE67433BD3C8C2',
 CREATE_INVENTORY_ID            TYPE /BOBF/DET_KEY VALUE '0242AC1100021EDF97CED14538E128C2',
      END OF ZI_INVENTORY_TP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_INVENTORY_TP                TYPE /BOBF/OBM_GROUP_KEY VALUE '0242AC1100021EDF97CE67433BD868C2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_INVENTORY_TP                TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EDF97CE6716D7B308C2',
 ZI_INVENTORY_TP_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EDF97CE6716D7B388C2',
 ZI_INVENTORY_TP_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EDF97CE6716D7B348C2',
 ZI_INVENTORY_TP_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100021EDF97CE6716D7B448C2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_INVENTORY_TP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  INVENTORY_ID                   TYPE STRING VALUE 'INVENTORY_ID',
  PRODUCT_ID                     TYPE STRING VALUE 'PRODUCT_ID',
  QUANTITY                       TYPE STRING VALUE 'QUANTITY',
  QUANTITY_UNIT                  TYPE STRING VALUE 'QUANTITY_UNIT',
  REMARK                         TYPE STRING VALUE 'REMARK',
  CREATED_AT                     TYPE STRING VALUE 'CREATED_AT',
      END OF ZI_INVENTORY_TP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_INVENTORY_TP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0242AC1100021EDF97CE6716D7B328C2',
      END OF ZI_INVENTORY_TP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_INVENTORY_TP,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '0242AC1100021EDF97CE67433BD408C2',
      END OF ZI_INVENTORY_TP,
    END OF SC_VALIDATION .
endinterface.